apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    env: dev
    project: impartus
    type: frontend

spec:
  containers: 
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80




